### ISSUE TITLE
Storyboard comments

### ISSUE THREAD

**Issue by haondt** [CMPUT301F18T01/MDBook#6]
storyboard needs to be updated with comments

**Comment by haondt** [comment]
Also arrows indicating the flow of the app as well as being reuploaded in a nice high-res format that allows the view to zoom in and see the parts in detail

**Comment by tcchan97** [comment]
Emailed Shaiful to see if using and Adobe XD link would work and plan for how storyboard should look.
"Hi Shaiful,

Yesterday you mentioned you wanted higher resolution picture for the storyboard. I was able to link our storyboard from Adobe XD which allow you to zoom and see clearer pictures, this interactive website also shows the control path your your mouse is over a storyboard. 

Given the link below, will this work?
https://xd.adobe.com/spec/b9aa885e-5ef6-4dce-48b3-c8d108a23d9c-cf9b/ 

I will also include pictures of the storyboard with annotations and storyboard flow in github. I will use what you mentioned yesterday were I would post the full storyboard but also show segments of the storyboard so you can see parts of it clearer.

Another Question we had was based on the feed back given to us about tool practice, we recieved 1/1.5 and you just mentioned we need to improve our mockup. shouldn't that be covered in the mock and storyboarding instead? Otherwise in what ways could we improve/address our tool practice feed back? "

**Comment by haondt** [comment]
shaifuls reply - Okay.. this is fine for now. Include all the info an link on GitHUB, and finish the storyboard flow.

**Comment by tcchan97** [comment]
Finished the storyboard on wiki
